version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - node.js/
    schedule:
      interval: daily
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    versioning-strategy: increase
