name: Sync README.md between node.js/ & node.js/docs/, then node.js/ to adamlui/js-utils/scss-to-css/node.js/

on:
  push:
    branches: [main]
    paths: [node.js/**]

permissions:
  contents: write

jobs:
  build:
    if: (github.repository == 'adamlui/scss-to-css') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/scss-to-css
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/scss-to-css
          path: adamlui/scss-to-css
          fetch-depth: 2

      - name: Checkout adamlui/js-utils
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/js-utils
          path: adamlui/js-utils

      - name: Sync README.md between node.js/ * node.js/docs
        run: |
          cd ${{ github.workspace }}/adamlui/scss-to-css

          # Init paths/content/mod timestamps
          root_readme="./node.js/README.md"
          root_readme_content=$(git show HEAD:"$root_readme")
          root_readme_modified=$(git log -1 --format="%ct" -- "$root_readme")
          docs_readme="./node.js/docs/README.md"
          docs_readme_content=$(git show HEAD:"$docs_readme")
          docs_readme_modified=$(git log -1 --format="%ct" -- "$docs_readme")

          # Perform syncs of diff READMEs
          if [[ "$root_readme_content" != "$docs_readme_content" ]] ; then
            if (( $root_readme_modified > $docs_readme_modified )) ; then
              cp -f "$root_readme" "$docs_readme"
              echo "Copied $root_readme to $docs_readme"
              src_folder="/node.js"
            elif (( $docs_readme_modified > $root_readme_modified )) ; then
              cp -f "$docs_readme" "$root_readme"
              echo "Copied $docs_readme to $root_readme"
              src_folder="/node.js/docs"
            fi
          fi

          # Expose sync src for commit msg in self-push step
          echo "SYNC_SRC=$src_folder" >> $GITHUB_ENV

      - name: Sync node.js/ to adamlui/js-utils/scss-to-css/node.js/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/scss-to-css/node.js/ \
            ${{ github.workspace }}/adamlui/js-utils/scss-to-css/node.js/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to adamlui/scss-to-css
        if: env.SYNC_SRC
        run: |
          cd ${{ github.workspace }}/adamlui/scss-to-css
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from ${{ env.SYNC_SRC }}]" || true
          git push

      - name: Push changes to adamlui/js-utils
        run: |
          cd ${{ github.workspace }}/adamlui/js-utils
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/scss-to-css]" || true
          git push
